services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mayprogulka
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secret_pass

  web:
    build: .
    # Команды теперь выполняются относительно /app/src (из-за WORKDIR в Dockerfile)
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app  # Пробрасываем всю папку backend
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: